version: "3.9"
name: profilx-loyalty-system

services:
  main-pg-db: 
    image: postgres:15
    container_name: main-pg-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: proFlixPassword12345678
      POSTGRES_DB: profilx_loyalty
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge