version: "3.9"
name: profilx-loyalty-system

services:
  main-pg-db: 
    image: postgres:15
    container_name: main-pg-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: proFlixPassword12345678
      POSTGRES_DB: profilx_loyalty
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - backend-network

  kafka-proflix-1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-proflix-1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-proflix-1:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka-proflix-1:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka-proflix-1:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-proflix-1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: MkQrZGIxNzFlNDhkNDQ1Mg
    networks:
      - backend-network

  kafka-ui-proflix:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-proflix
    depends_on:
      - kafka-proflix-1
    ports:
      - "7500:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-proflix-1:29092
    networks:
      - backend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge