CREATE TABLE IF NOT EXISTS user_roles(
  id serial PRIMARY KEY,
  role_code VARCHAR (20) UNIQUE NOT NULL,
  role_name VARCHAR (100) UNIQUE NOT NULL,
  description VARCHAR (300) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);