CREATE TABLE IF NOT EXISTS users(
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR (50) UNIQUE NOT NULL,
  email VARCHAR (300) UNIQUE NOT NULL,
  password_hash VARCHAR (255) NOT NULL,
  fullname VARCHAR (100) NOT NULL,
  role_id INTEGER NOT NULL,
  status SMALLINT NOT NULL,
  last_login_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  is_deleted BOOLEAN DEFAULT FALSE,
  deleted_at TIMESTAMP WITH TIME ZONE 
);

ALTER TABLE users
ADD CONSTRAINT fk_role_id FOREIGN KEY (role_id)
  REFERENCES user_roles (id)
  ON UPDATE NO ACTION;

COMMENT ON COLUMN users.status IS 'User status: 1=ACTIVE, 2=SUSPENDED, 3=DISABLED';