CREATE TABLE IF NOT EXISTS wallets(
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  member_id UUID NOT NULL,
  wallet_type SMALLINT NOT NULL DEFAULT 1,
  balance INTEGER DEFAULT 0 NOT NULL CHECK (balance >= 0),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  is_deleted BOOLEAN DEFAULT FALSE,
  deleted_at TIMESTAMP WITH TIME ZONE 
);

COMMENT ON COLUMN wallets.wallet_type IS 'Wallet type: 1=MAIN, 2=EVENT1, 3=EVENT2';

ALTER TABLE wallets
ADD CONSTRAINT fk_member_id FOREIGN KEY (member_id)
  REFERENCES members (id)
  ON UPDATE NO ACTION;